### ISSUE TITLE
binary is not a Firefox executable

### ISSUE THREAD

**Issue by felipe-veras-araujo** [eduardonery1/ani-tupi#1]
Estou tentando assistir algum episódio para testar e estou recebendo este erro:

Procurando video em: https://animefire.plus/animes/one-piece/1
Traceback (most recent call last):
  File "main.py", line 39, in <module>
  File "selenium/webdriver/firefox/webdriver.py", line 71, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 238, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 325, in start_session
  File "selenium/webdriver/remote/webdriver.py", line 380, in execute
  File "selenium/webdriver/remote/errorhandler.py", line 229, in check_response
selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable

[PYI-12762:ERROR] Failed to execute script 'main' due to unhandled exception!

Browser = Firefox

**Comment by eduardonery1** [comment]
Poderia dizer também sua versão do firefox e distro para que eu possa reproduzir o erro.

**Comment by eduardonery1** [comment]
Você está usando um snap do firefox?

**Comment by eduardonery1** [comment]
Testei uma solução no ubuntu e acredito que resolvi o problema, de git pull e ./build.sh, isso deve resolver.
